// src/main/java/com/school/sms/model/FeePayment.java

package com.school.sms.model;

import jakarta.persistence.*;
import lombok.*;
import java.time.LocalDate;
import java.time.LocalDateTime;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "fee_payments", indexes = {
    @Index(name = "idx_fee_payments_student_id", columnList = "student_id"),
    @Index(name = "idx_fee_payments_receipt", columnList = "receiptNumber"),
    @Index(name = "idx_fee_payments_student_year", columnList = "student_id, academic_year_id"),
    @Index(name = "idx_fee_payments_created_at", columnList = "created_at")
})
@EqualsAndHashCode(callSuper = true)
public class FeePayment extends SoftDeletableEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne
    @JoinColumn(name = "student_id", nullable = false)
    private Student student;

    @ManyToOne
    @JoinColumn(name = "fee_structure_id")
    private FeeStructure feeStructure;

    /**
     * Structured receipt number: SCHOOL_CODE/YEAR/000001
     * Generated by ReceiptNumberService using a DB-locked sequence counter.
     * NEVER use System.currentTimeMillis() here — that allows gaps and duplicates.
     */
    @Column(unique = true)
    private String receiptNumber;

    private Double amount;
    private LocalDate paymentDate;
    private String paymentMethod;  // CASH, ONLINE, CHEQUE
    private String transactionId;  // For online payments
    private String month;          // "January 2024"

    @Enumerated(EnumType.STRING)
    private PaymentStatus status;  // PAID, PENDING, OVERDUE

    private String remarks;

    /**
     * Academic year this payment belongs to.
     * Required — prevents cross-year fee aggregation errors.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "academic_year_id")
    private AcademicYear academicYear;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "branch_id")
    private Branch branch;

    @Column(updatable = false)
    private LocalDateTime createdAt;

    @PrePersist
    public void prePersist() {
        createdAt = LocalDateTime.now();
        // receiptNumber is set BEFORE persist by ReceiptNumberService.
        // The old fallback (System.currentTimeMillis) is intentionally removed.
        if (receiptNumber == null || receiptNumber.isBlank()) {
            throw new IllegalStateException(
                "Receipt number must be assigned before persisting FeePayment. " +
                "Use ReceiptNumberService.nextReceiptNumber() in the service layer."
            );
        }
    }
}