// src/schema/studentSchema.js
import React from 'react';
import { entitySchema } from './schemaEngine';
import { User, Phone, Mail, Calendar, BookOpen } from 'lucide-react';

/**
 * Student Domain Schema
 */
export const studentSchema = entitySchema({
  entity: "student",

  permissions: {
    table: "STUDENTS_VIEW",
    form: "STUDENTS_EDIT",
    delete: "STUDENTS_DELETE",
    export: "STUDENTS_EXPORT"
  },

  fields: [
    {
      key: "studentId",
      label: "ID",
      showInForm: false, // Auto-generated by backend
      width: "120px",
      render: (val) => <span className="font-black text-slate-900">{val}</span>
    },
    {
      key: "firstName",
      label: "First Name",
      required: true,
      filterable: true,
      render: (val, row) => (
        <div className="flex items-center gap-3">
          <div className="w-8 h-8 rounded-lg bg-blue-50 text-blue-600 flex items-center justify-center font-bold text-xs">
            {val?.charAt(0)}
          </div>
          <span className="font-bold text-slate-700">{val}</span>
        </div>
      )
    },
    {
      key: "lastName",
      label: "Last Name",
      required: true,
      filterable: true
    },
    {
      key: "email",
      label: "Email",
      type: "email",
      required: true,
      filterable: true,
      render: (val) => (
        <div className="flex items-center gap-2 text-slate-500">
           <Mail size={14} />
           <span className="text-xs">{val}</span>
        </div>
      )
    },
    {
      key: "phone",
      label: "Phone",
      type: "tel",
      render: (val) => (
        <div className="flex items-center gap-2 text-slate-500">
           <Phone size={14} />
           <span className="text-xs">{val}</span>
        </div>
      )
    },
    {
      key: "classRoom",
      label: "Class",
      type: "select",
      filterable: true,
      filterType: "select",
      options: [], // Populated at runtime
      render: (val) => (
        <div className="inline-flex items-center gap-2 px-2 py-1 bg-slate-100 rounded-lg text-slate-600 font-bold text-[10px] uppercase">
          <BookOpen size={12} />
          {val?.name} {val?.section}
        </div>
      )
    },
    {
      key: "gender",
      label: "Gender",
      type: "select",
      options: [
        { label: "Male", value: "MALE" },
        { label: "Female", value: "FEMALE" },
        { label: "Other", value: "OTHER" }
      ],
      showInTable: false
    },
    {
      key: "dateOfBirth",
      label: "DOB",
      type: "date",
      showInTable: false
    },
    {
      key: "status",
      label: "Status",
      type: "select",
      options: [
        { label: "Active", value: "ACTIVE" },
        { label: "Inactive", value: "INACTIVE" },
        { label: "Alumni", value: "ALUMNI" }
      ],
      filterable: true,
      render: (val) => (
        <span className={`px-2 py-1 rounded-full text-[10px] font-black uppercase tracking-widest
          ${val === 'ACTIVE' ? 'bg-green-100 text-green-700' : 'bg-red-100 text-red-700'}`}>
          {val}
        </span>
      )
    }
  ],

  actions: [
    { key: "view", label: "View Details", scope: "row" },
    { key: "edit", label: "Edit Profile", scope: "row" },
    { key: "delete", label: "Delete", scope: "row", variant: "danger" },
    { key: "promote", label: "Promote", scope: "bulk" },
    { key: "archive", label: "Archive", scope: "bulk" }
  ],

  routes: {
    list: "/admin/students",
    create: "/admin/students/new",
    detail: "/admin/students/:id",
    edit: "/admin/students/:id/edit"
  }
});
